version: 1.0.{build}-{branch}

image:
  - Visual Studio 2015
  # - Visual Studio 2017

artifacts:
  - path: build\**\*.tar.gz
    name: camaro

environment:
  github_release_token:
    secure: PbRZg8hVpAS5WWNZYY461xJOOgZLaDIR8QGM5fX+o11JCLoR+ccdwkbBHldTBcBx
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"

matrix:
  fast_finish: true

platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - npm config set spin false
  - npm i -g npm node-pre-gyp --production
  - npm install

test_script:
  - npm test

after_test:
  - node-pre-gyp package 2>&1

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: camaro
    auth_token: $(github_release_token)
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true